// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.1
// source: mcp.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InstructionService_SendInstruction_FullMethodName   = "/mcp.InstructionService/SendInstruction"
	InstructionService_StreamInstruction_FullMethodName = "/mcp.InstructionService/StreamInstruction"
)

// InstructionServiceClient is the client API for InstructionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InstructionService defines the core API for AgentD
type InstructionServiceClient interface {
	SendInstruction(ctx context.Context, in *InstructionRequest, opts ...grpc.CallOption) (*InstructionResponse, error)
	StreamInstruction(ctx context.Context, in *InstructionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstructionResponse], error)
}

type instructionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInstructionServiceClient(cc grpc.ClientConnInterface) InstructionServiceClient {
	return &instructionServiceClient{cc}
}

func (c *instructionServiceClient) SendInstruction(ctx context.Context, in *InstructionRequest, opts ...grpc.CallOption) (*InstructionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstructionResponse)
	err := c.cc.Invoke(ctx, InstructionService_SendInstruction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instructionServiceClient) StreamInstruction(ctx context.Context, in *InstructionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstructionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InstructionService_ServiceDesc.Streams[0], InstructionService_StreamInstruction_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InstructionRequest, InstructionResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InstructionService_StreamInstructionClient = grpc.ServerStreamingClient[InstructionResponse]

// InstructionServiceServer is the server API for InstructionService service.
// All implementations must embed UnimplementedInstructionServiceServer
// for forward compatibility.
//
// InstructionService defines the core API for AgentD
type InstructionServiceServer interface {
	SendInstruction(context.Context, *InstructionRequest) (*InstructionResponse, error)
	StreamInstruction(*InstructionRequest, grpc.ServerStreamingServer[InstructionResponse]) error
	mustEmbedUnimplementedInstructionServiceServer()
}

// UnimplementedInstructionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInstructionServiceServer struct{}

func (UnimplementedInstructionServiceServer) SendInstruction(context.Context, *InstructionRequest) (*InstructionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendInstruction not implemented")
}
func (UnimplementedInstructionServiceServer) StreamInstruction(*InstructionRequest, grpc.ServerStreamingServer[InstructionResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamInstruction not implemented")
}
func (UnimplementedInstructionServiceServer) mustEmbedUnimplementedInstructionServiceServer() {}
func (UnimplementedInstructionServiceServer) testEmbeddedByValue()                            {}

// UnsafeInstructionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InstructionServiceServer will
// result in compilation errors.
type UnsafeInstructionServiceServer interface {
	mustEmbedUnimplementedInstructionServiceServer()
}

func RegisterInstructionServiceServer(s grpc.ServiceRegistrar, srv InstructionServiceServer) {
	// If the following call pancis, it indicates UnimplementedInstructionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InstructionService_ServiceDesc, srv)
}

func _InstructionService_SendInstruction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstructionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstructionServiceServer).SendInstruction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstructionService_SendInstruction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstructionServiceServer).SendInstruction(ctx, req.(*InstructionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstructionService_StreamInstruction_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InstructionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InstructionServiceServer).StreamInstruction(m, &grpc.GenericServerStream[InstructionRequest, InstructionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InstructionService_StreamInstructionServer = grpc.ServerStreamingServer[InstructionResponse]

// InstructionService_ServiceDesc is the grpc.ServiceDesc for InstructionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InstructionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcp.InstructionService",
	HandlerType: (*InstructionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendInstruction",
			Handler:    _InstructionService_SendInstruction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamInstruction",
			Handler:       _InstructionService_StreamInstruction_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mcp.proto",
}
